### ISSUE TITLE
Update template for `106`

### ISSUE THREAD

**Issue by trickypr** [pulse-browser/gluon#23]
The template contains failing patches for `106``

**Comment by splatboydev** [comment]
The patches aren't failing, but the top bar still ends up like this without any changes to the source/patches.
This might(?) be an issue with Windows but on Pulse this seems to work fine.
![image](https://user-images.githubusercontent.com/64037464/200178504-d6952b48-a8e1-4e3b-bb9a-5e4ea29c3973.png)

**Comment by splatboydev** [comment]
Pulse: 
![image](https://user-images.githubusercontent.com/64037464/200178566-503a8ddf-7a77-4376-9f5d-6b103a98ee63.png)
Firefox:
![image](https://user-images.githubusercontent.com/64037464/200178848-62e0d884-7593-4236-8cfd-ab94dfd3d576.png)
