### ISSUE TITLE
Gluon package fails with Python >=3

### ISSUE THREAD

**Issue by splatboydev** [pulse-browser/gluon#34]
Tested on Windows 11 latest, on MozillaBuild latest.
This is fixed if you change the code in base.py to __next__().
![image](https://user-images.githubusercontent.com/64037464/211999850-5cb03361-7829-43e6-8cba-65e04fc78e5c.png)

**Comment by trickypr** [comment]
This is an upstream error with mach, where malformed `-j#` args will cause mach to crash. If you are using the make `-j` command, ensure that the number is directly after the "j". For example, `-j4` works, but `-j 4` will crash.

As a side note, you should avoid specifying how many threads your build uses unless mach crashes for some reason. Mach will already try and push the most out of your system (e.g. if you have 16 threads, mach will run on all 16 threads, given you have 1GB of ram per thread). The only reason to use `-j` or similar is if you are running into OOM crashes or your system miss-reporting core count.

**Comment by splatboydev** [comment]
I don't use -j, actually. I generally just change the MOZ_PARALLEL_BUILD variable but that seems to be a shorthand for specifying -j.
