### ISSUE TITLE
Custom CSS imports

### ISSUE THREAD

**Issue by PressJump** [pulse-browser/gluon#39]
It looks like the custom css routes are improperly routed or something else is going on as the shared route under custom does not apply to version 113.

**Comment by PressJump** [comment]
Do you know anything about this @trickypr ?

**Comment by trickypr** [comment]
Those patches are from ages ago and are not the most efficient way of applying themes. You should distribute your theme via an addon in the same way that Pulse does.

(tl;dr: Go steal Pulse's code because it is actually maintained)
