### ISSUE TITLE
about gluon ...

### ISSUE THREAD

**Issue by ioc2e3** [pulse-browser/gluon#46]
Will there be a Windows version?

Will there be a Portable version?

Will there be a Traditional Chinese interface?

.

**Comment by trickypr** [comment]
Windows version: Yes. Building on windows is a nightmare. Here are the instructions for getting setup: https://docs.gluon.dev/guides/windows/

Portable version: If you have npm, you can install it just like any other npm package, in the same way that [pulse does](https://github.com/pulse-browser/browser/blob/123c6e0884cf40efddc725bd48e0f9bc18c05fe2/package.json#L10)

Traditional Chinese interface: I do not speak or write any form of Chinese. If you can provide a translation that is reviewed by one other person with significant open source contributions, I will accept it.

**Comment by ioc2e3** [comment]
> Windows 版本：是的。在 Windows 上建置是一場噩夢。以下是設定說明：https://docs.gluon.dev/guides/windows/
> 
> 便攜式版本：如果您有 npm，則可以像安裝任何其他 npm 軟體包一樣安裝它，就像[脈衝一樣](https://github.com/pulse-browser/browser/blob/123c6e0884cf40efddc725bd48e0f9bc18c05fe2/package.json#L10)
> 
> 繁體中文介面：我不會說或寫任何形式的中文。如果您可以提供由一位對開源做出重大貢獻的其他人審查的翻譯，我會接受。

Very regrettable ...

In addition to promoting open source software ...

No one I know has contributed anything else to open source ...

.
