### ISSUE TITLE
unknown error? help

### ISSUE THREAD

**Issue by 777Vincent** [pulse-browser/gluon#47]
WARNING It is recommended that you provide a `binaryName` field in your config file, otherwise packaging may get messed up
00:00:00 Bootstrapping NexBen...
Passing through to |mach bootstrap|
00:00:02 fatal: your current branch 'nexben' does not have any commits yet
00:00:02 Error running mach:
00:00:02
00:00:02     mach bootstrap --application-choice browser
00:00:02
00:00:02 The error occurred in code that was called by the mach command. This is either
00:00:02 a bug in the called code itself or in the way that mach is calling it.
00:00:02 You can invoke ``./mach busted`` to check if this issue is already on file. If it
00:00:02 isn't, please use ``./mach busted file bootstrap`` to report it. If ``./mach busted`` is
00:00:02 misbehaving, you can also inspect the dependencies of bug 1543241.
00:00:02
00:00:02 If filing a bug, please include the full output of mach, including this error
00:00:02 message.
00:00:02
00:00:02 The details of the failure are as follows:
00:00:02
00:00:02 subprocess.CalledProcessError: Command '('C:\\Program Files\\Git\\cmd\\git.EXE', 'log', '-1', '--format=%ct')' returned non-zero exit status 128.
00:00:02
00:00:02   File "C:\Users\alexa\Downloads\nexben\engine\python\mozboot\mozboot\mach_commands.py", line 50, in bootstrap
00:00:02     bootstrapper.bootstrap(command_context.settings)
00:00:02   File "c:\users\alexa\downloads\nexben\engine\python\mozboot\mozboot\bootstrap.py", line 414, in bootstrap
00:00:02     (checkout_type, checkout_root) = current_firefox_checkout(
00:00:02                                      ^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:02   File "c:\users\alexa\downloads\nexben\engine\python\mozboot\mozboot\bootstrap.py", line 684, in current_firefox_checkout
00:00:02     _warn_if_risky_revision(path)
00:00:02   File "c:\users\alexa\downloads\nexben\engine\python\mozboot\mozboot\bootstrap.py", line 833, in _warn_if_risky_revision
00:00:02     if (time.time() - repo.get_commit_time()) >= NUM_SECONDS_IN_MONTH:
00:00:02                       ^^^^^^^^^^^^^^^^^^^^^^
00:00:02   File "c:\users\alexa\downloads\nexben\engine\python\mozversioncontrol\mozversioncontrol\__init__.py", line 744, in get_commit_time
00:00:02     return int(self._run("log", "-1", "--format=%ct").strip())
00:00:02                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:02   File "c:\users\alexa\downloads\nexben\engine\python\mozversioncontrol\mozversioncontrol\__init__.py", line 110, in _run
00:00:02     return subprocess.check_output(
00:00:02            ^^^^^^^^^^^^^^^^^^^^^^^^
00:00:02   File "C:\Users\alexa\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 465, in check_output
00:00:02     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
00:00:02            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:00:02   File "C:\Users\alexa\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
00:00:02     raise CalledProcessError(retcode, process.args,

**Comment by trickypr** [comment]
Your `gluon download` failed. Fix that and retry
