### ISSUE TITLE
gluon import and gluon build are bugged.

### ISSUE THREAD

**Issue by VitaOS-Official** [pulse-browser/gluon#50]
![image](https://github.com/user-attachments/assets/94b1f098-6bd6-4c21-8f30-e14dfc619cf9)

I'm not sure what happened here, only that it happened.

**Comment by VitaOS-Official** [comment]
Fixed, all you have to do is keep everything in one folder and right click file explorer > open git bash here and create src file yourself

**Comment by splatboydev** [comment]
Regardless, gluon is no longer being maintained.
